=== Armedia/Caliente/engine/impl/alfresco-bi/src/main/resources/alfresco-bi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd" targetNamespace="http://www.armedia.com/ns/caliente/engine/alfresco-bi"
	xmlns:tns="http://www.armedia.com/ns/caliente/engine/alfresco-bi" elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0">

	<xsd:simpleType name="noSpaces.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
			<xsd:whiteSpace value="collapse" />
			<xsd:pattern value="[^\s]+" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="trimmed_string.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
			<xsd:whiteSpace value="collapse" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="empty_trimmed_string.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="0" />
			<xsd:whiteSpace value="collapse" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="version_number.t">
		<xsd:restriction base="xsd:decimal">
			<xsd:minInclusive value="0.0" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="singleChar.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
			<xsd:maxLength value="1" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="residualsMode.t" final="restriction">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="MANDATORY" />
			<xsd:enumeration value="INCLUDE" />
			<xsd:enumeration value="EXCLUDE" />
			<xsd:enumeration value="REJECT" />
		</xsd:restriction>
	</xsd:simpleType>


	<xsd:complexType name="version.t">
		<xsd:sequence>
			<xsd:element name="number" type="tns:version_number.t" minOccurs="1" maxOccurs="1" />
			<xsd:element name="content" type="tns:trimmed_string.t" minOccurs="0" maxOccurs="1" />
			<xsd:element name="metadata" type="tns:trimmed_string.t" minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="versions.t">
		<xsd:sequence>
			<xsd:element name="version" type="tns:version.t" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="item.t">
		<xsd:sequence>
			<xsd:element name="directory" type="xsd:boolean" minOccurs="1" maxOccurs="1" />
			<xsd:element name="sourcePath" type="tns:empty_trimmed_string.t" minOccurs="1" maxOccurs="1" />
			<xsd:element name="sourceName" type="tns:trimmed_string.t" minOccurs="1" maxOccurs="1" />
			<xsd:element name="targetPath" type="tns:empty_trimmed_string.t" minOccurs="1" maxOccurs="1" />
			<xsd:element name="targetName" type="tns:trimmed_string.t" minOccurs="1" maxOccurs="1" />
			<xsd:element name="versions" type="tns:versions.t" minOccurs="1" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="scan.t">
		<xsd:sequence>
			<xsd:element name="item" type="tns:item.t" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="version" type="tns:version.t" />
	<xsd:element name="item" type="tns:item.t" />
	<xsd:element name="scan" type="tns:scan.t" />

	<xsd:complexType name="emptyElement.t">
		<xsd:complexContent>
			<xsd:restriction base="xsd:anyType" />
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="mapping.t">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="tgt" type="tns:noSpaces.t" use="required" />
				<xsd:attribute name="caseSensitive" type="xsd:boolean" use="optional" default="true" />
				<xsd:attribute name="separator" type="tns:singleChar.t" use="optional" default="," />
				<xsd:attribute name="override" type="xsd:boolean" use="optional" default="false" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="includeNamed.t">
		<xsd:simpleContent>
			<xsd:extension base="xsd:IDREF" />
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="mappingName.t">
		<xsd:complexContent>
			<xsd:extension base="tns:mapping.t"/>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="setValue.t">
		<xsd:complexContent>
			<xsd:extension base="tns:mapping.t"/>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="mappingNamespace.t">
		<xsd:complexContent>
			<xsd:extension base="tns:mapping.t"/>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="mappingSet.t">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="map" type="tns:mappingName.t" />
				<xsd:element name="include" type="tns:includeNamed.t" />
				<xsd:element name="set" type="tns:setValue.t" />
				<xsd:element name="nsmap" type="tns:mappingNamespace.t" />
			</xsd:choice>
			<xsd:choice minOccurs="0" maxOccurs="1">
				<xsd:element name="residuals" type="tns:residualsMode.t" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="separator" type="tns:singleChar.t" use="optional" default="," />
	</xsd:complexType>

	<xsd:complexType name="namedMappings.t">
		<xsd:complexContent>
			<xsd:extension base="tns:mappingSet.t">
				<xsd:attribute name="name" type="xsd:ID" use="required" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="typeMappings.t">
		<xsd:complexContent>
			<xsd:extension base="tns:mappingSet.t">
				<xsd:attribute name="name" type="tns:noSpaces.t" use="required" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="attributeMappings.t">
		<xsd:sequence>
			<xsd:element name="common-mappings" type="tns:mappingSet.t" minOccurs="0" maxOccurs="1" />
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="named-mappings" type="tns:namedMappings.t" />
				<xsd:element name="type-mappings" type="tns:typeMappings.t" />
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="attribute-mappings" type="tns:attributeMappings.t">
		<xsd:unique name="uniqueTypeMappingName">
			<xsd:selector xpath="tns:type-mappings"/>
			<xsd:field xpath="@name"/>
		</xsd:unique>
	</xsd:element>
	
	<xsd:complexType name="principalMappingAttributes.t">
		<xsd:sequence>
			<xsd:element name="attribute" type="tns:noSpaces.t" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="principalMappings.t">
		<xsd:sequence>
			<xsd:element name="user" type="tns:principalMappingAttributes.t" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="group" type="tns:principalMappingAttributes.t" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="role" type="tns:principalMappingAttributes.t" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="principal-mappings" type="tns:principalMappings.t">
		<xsd:unique name="uniqueAttributeReference">
			<xsd:selector xpath="*/tns:attribute"/>
			<xsd:field xpath="."/>
		</xsd:unique>
	</xsd:element>
</xsd:schema>

=== Armedia/Caliente/engine/impl/alfresco-bi/edms-mappings.xml
<?xml version="1.0" encoding="UTF-8"?>
<attribute-mappings xmlns="http://www.armedia.com/ns/caliente/engine/alfresco-bi" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.armedia.com/ns/caliente/engine/alfresco-bi platform:/resource/caliente-engine-alfresco-bi/src/main/resources/alfresco-bi.xsd">

	<type-mappings name="edms:doc">
		<map tgt="cm:created">ucm:xGSADocumentCreateDate</map>
		<map tgt="cm:creator">ucm:xGSADocumentCreatedBy</map>
		<map tgt="cm:modified">ucm:xGSADocumentUpdateDate</map>
		<map tgt="cm:modifier">ucm:xGSADocumentUpdatedBy</map>
		<map tgt="cm:name">ucm:fFileName,ucm:dOriginalName</map>
		<map tgt="cm:title">ucm:dDocTitle</map>
		<map tgt="edms:buildingname" caseSensitive="false">building_name</map>
		<map tgt="edms:buildingnumber2" caseSensitive="false">building_number_2</map>
		<map tgt="edms:buildingnumber" caseSensitive="false">bld_id_pk</map>
		<map tgt="edms:buildingstatus" caseSensitive="false">building_status</map>
		<map tgt="edms:city" caseSensitive="false">city</map>
		<map tgt="edms:county" caseSensitive="false">county</map>
		<map tgt="edms:customercode">ucm:xGSAAgencyBureauCode</map>
		<map tgt="edms:customername" caseSensitive="false">agency_bureau_name</map>
		<map tgt="edms:fieldofficename" caseSensitive="false">field_office_desc</map>
		<map tgt="edms:fiscalyear">ucm:xGSAProcessedDate</map>
		<map tgt="edms:leasenumber">ucm:xGSALeaseNumber</map>
		<map tgt="edms:location">ucm:xGSARegionId</map>
		<map tgt="edms:owner">ucm:xGSADocumentCreatedBy</map>
		<map tgt="edms:pbsregion">ucm.xGSARegionId</map>
		<map tgt="edms:projectmanager" caseSensitive="false">project_manager</map>
		<map tgt="edms:projectnumber">ucm:xGSAProjectNumber</map>
		<map tgt="edms:projecttitle" caseSensitive="false">project_title</map>
		<map tgt="edms:servicecenter" caseSensitive="false">service_center_name</map>
		<map tgt="edms:state" caseSensitive="false">state_cd</map>
		<map tgt="edms:streetaddress2" caseSensitive="false">address2</map>
		<map tgt="edms:streetaddress" caseSensitive="false">street_address</map>
		<map tgt="edms:zipcode" caseSensitive="false">zip_code</map>
		<set tgt="edms:function">Real Property Management</set>
		<set tgt="edms:organization">PR</set>
	</type-mappings>

	<type-mappings name="edms:leasing">
		<map tgt="edms:oanumber">ucm:xGSAOANumber</map>
		<map tgt="edms:appiandocid">ucm:xGSAAppianDocumentId</map>
		<map tgt="edms:appianuniversaldocid">ucm:xGSAAppianUniversalDocumentId</map>
	</type-mappings>

	<type-mappings name="edms:buildingproject">
		<set tgt="edms:businessline">Leasing</set>
	</type-mappings>

	<type-mappings name="edms:leasecontracting">
		<map tgt="edms:closeddate" caseSensitive="false">expiration_dt</map>
		<set tgt="edms:contracttype">Lease</set>
		<map tgt="edms:projectmanager" caseSensitive="false">project_manager</map>
		<map tgt="edms:tab">ucm:xGSAEleasePhaseName</map>
	</type-mappings>

</attribute-mappings>

=== Armedia/Caliente/engine/impl/alfresco-bi/src/test/resources/test-principal-mappings.xml
<?xml version="1.0" encoding="UTF-8"?>
<principal-mappings xmlns="http://www.armedia.com/ns/caliente/engine/alfresco-bi" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.armedia.com/ns/caliente/engine/alfresco-bi platform:/resource/caliente-engine-alfresco-bi/src/main/resources/alfresco-bi.xsd">

	<user>
		<attribute>abc1</attribute>
	</user>
	<group>
		<attribute>abc2</attribute>
	</group>
	<role>
		<attribute>abc3</attribute>
		<attribute>abc4</attribute>
	</role>

</principal-mappings>
