=== Armedia/Caliente/engine/impl/alfresco-bi/src/main/resources/properties.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd"
	targetNamespace="http://java.sun.com/dtd/properties.dtd"
	xmlns:tns="http://java.sun.com/dtd/properties.dtd" elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0">

	<xsd:annotation>
		<xsd:documentation>Properties Files alternate schema</xsd:documentation>
	</xsd:annotation>

	<xsd:complexType name="comment.t">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string" />
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="entry.t">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="key" type="xsd:string" use="required" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="properties.t">
		<xsd:sequence>
			<xsd:element name="comment" type="tns:comment.t" minOccurs="0" maxOccurs="1" />
			<xsd:element name="entry" type="tns:entry.t" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="comment" type="tns:comment.t" />
	<xsd:element name="entry" type="tns:entry.t" />
	<xsd:element name="properties" type="tns:properties.t" />
</xsd:schema>

=== Armedia/Caliente/engine/impl/alfresco-bi/src/main/resources/properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<properties xmlns="http://java.sun.com/dtd/properties.dtd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/dtd/properties.dtd properties.xsd ">

	<comment>comment</comment>
	<entry key="sdfasdf">asdfasdfasd</entry>

	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
	<entry key="sdfasdf">asdfasdfasd</entry>
</properties>
