=== Armedia/Caliente/store/api/src/main/resources/stores.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd"
	targetNamespace="http://www.armedia.com/ns/caliente/stores"
	xmlns:tns="http://www.armedia.com/ns/caliente/stores" elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0">

	<xsd:simpleType name="trimmed_string.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
			<xsd:whiteSpace value="collapse" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="class_name.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
			<xsd:whiteSpace value="collapse" />
			<xsd:pattern value="([a-zA-Z_$][a-zA-Z\d_$]*\.)*[a-zA-Z_$][a-zA-Z\d_$]*"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="id_string.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
			<xsd:whiteSpace value="collapse" />
			<xsd:pattern value="[\w_]+"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="settingName.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
			<xsd:whiteSpace value="collapse" />
			<xsd:pattern value="[\w_.]+"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="empty_trimmed_string.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="0" />
			<xsd:whiteSpace value="collapse" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="setting.t">
		<xsd:simpleContent>
			<xsd:extension base="tns:trimmed_string.t">
				<xsd:attribute name="name" type="tns:settingName.t" use="required"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="settings.t">
		<xsd:sequence>
			<xsd:element name="setting" type="tns:setting.t" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="store.t">
		<xsd:sequence>
			<xsd:element name="parent" type="tns:id_string.t" minOccurs="0" maxOccurs="1" />
			<xsd:element name="type" type="tns:class_name.t" minOccurs="1" maxOccurs="1" />
			<xsd:element name="prep" type="tns:class_name.t" minOccurs="0" maxOccurs="1" />
			<xsd:element name="settings" type="tns:settings.t" minOccurs="0" maxOccurs="1"/>
			<!--
			<xsd:element name="configuration" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			-->
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:id_string.t" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="stores.t">
		<xsd:sequence>
			<xsd:element name="settings" type="tns:settings.t" minOccurs="0" maxOccurs="1" />
			<xsd:element name="objectstore" type="tns:store.t" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="contentstore" type="tns:store.t" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="stores" type="tns:stores.t"/>
</xsd:schema>

=== Armedia/Caliente/cli/caliente/src/main/resources/META-INF/com/armedia/caliente/stores.xml
<?xml version="1.0" encoding="UTF-8"?>
<stores xmlns="http://www.armedia.com/ns/caliente/stores"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.armedia.com/ns/caliente/stores http://www.armedia.com/ns/caliente/stores.xsd">
	<settings>
		<setting name="target">${user.dir}/caliente</setting>
		<setting name="dir.metadata">${dir.root}/db</setting>
		<setting name="dir.content">${dir.root}/streams</setting>
		<setting name="dir.content.organizer">hierarchical</setting>

		<!-- H2 Support -->
		<setting name="db.driver">org.h2.Driver</setting>
		<setting name="db.type">h2</setting>
		<!-- TODO: Add ;IFEXISTS=TRUE here but only for import mode? -->
		<setting name="db.flags">AUTO_SERVER=TRUE;MODE=PostgreSQL;DATABASE_TO_LOWER=FALSE;DEFAULT_NULL_ORDERING=HIGH;TRACE_LEVEL_FILE=4;CACHE_SIZE=262144</setting>
	</settings>

	<objectstore id="default">
		<type>jdbc</type>
		<settings>
			<setting name="location.type">pooled</setting>
			<setting name="jdbc.url">jdbc:${db.type}:${dir.metadata}/${db.name};${db.flags}</setting>
			<setting name="jdbc.driver">${db.driver}</setting>
		</settings>
	</objectstore>

	<contentstore id="default">
		<type>local</type>
		<settings>
			<setting name="base.dir">${dir.content}</setting>
			<setting name="uri.organizer">${dir.content.organizer}</setting>
			<setting name="force.safe.filenames">false</setting>
			<setting name="safe.filename.encoding">UTF-8</setting>
			<setting name="fix.filenames">true</setting>
			<setting name="fail.on.collisions">false</setting>
			<setting name="ignore.extra.filename.info">false</setting>
			<setting name="use.windows.fix">true</setting>
		</settings>
	</contentstore>

	<contentstore id="direct">
		<type>local</type>
		<settings>
			<setting name="base.dir">${dir.content}</setting>
			<setting name="uri.organizer">localfs</setting>
			<setting name="force.safe.filenames">false</setting>
			<setting name="safe.filename.encoding">UTF-8</setting>
			<setting name="fix.filenames">true</setting>
			<setting name="use.windows.fix">true</setting>
			<setting name="fail.on.collisions">false</setting>
			<setting name="ignore.descriptor">true</setting>
		</settings>
	</contentstore>
</stores>

=== Armedia/Caliente/engine/impl/ucm/src/test/resources/META-INF/com/armedia/caliente/stores.xml
<?xml version="1.0" encoding="UTF-8"?>
<stores xmlns="http://www.armedia.com/ns/caliente/stores"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.armedia.com/ns/caliente/stores platform:/resource/caliente-store/src/main/resources/stores.xsd">
	<settings>
		<setting name="target">${user.dir}/target/test-db</setting>
		<setting name="db.name">cmis-test</setting>
		<setting name="dir.metadata">${target}</setting>
		<setting name="dir.content">${target}/content</setting>
		<setting name="dir.content.organizer">cmis</setting>
	</settings>

	<objectstore id="default">
		<type>jdbc</type>
		<settings>
			<setting name="location.type">pooled</setting>
			<setting name="jdbc.url">jdbc:h2:${dir.metadata}/${db.name};AUTO_SERVER=TRUE;MODE=PostgreSQL;PAGE_SIZE=4096</setting>
			<setting name="jdbc.driver">org.h2.Driver</setting>
		</settings>
	</objectstore>

	<contentstore id="default">
		<type>local</type>
		<settings>
			<setting name="base.dir">${dir.content}</setting>
			<setting name="uri.organizer">${dir.content.organizer}</setting>
			<setting name="force.safe.filenames">false</setting>
			<setting name="safe.filename.encoding">UTF-8</setting>
			<setting name="fix.filenames">true</setting>
			<setting name="fail.on.collisions">false</setting>
			<setting name="ignore.extra.filename.info">false</setting>
			<setting name="use.windows.fix">true</setting>
		</settings>
	</contentstore>
</stores>
