=== Armedia/Caliente/engine/impl/trunk/src/main/resources/import.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd" targetNamespace="http://www.armedia.com/ns/cmf/engines/xml/import"
	xmlns:tns="http://www.armedia.com/ns/cmf/engines/xml/import" elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0">

	<xsd:simpleType name="trimmed_string.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="0" />
			<xsd:whiteSpace value="collapse" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="positiveInt.t">
		<xsd:restriction base="xsd:int">
			<xsd:minInclusive value="1" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="class_name.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
			<xsd:whiteSpace value="collapse" />
			<xsd:pattern value="([a-zA-Z_$][a-zA-Z\d_$]*\.)*[a-zA-Z_$][a-zA-Z\d_$]*" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="id_string.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
			<xsd:whiteSpace value="collapse" />
			<xsd:pattern value="[\w_]+" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="propertyName.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
			<xsd:whiteSpace value="collapse" />
			<xsd:pattern value="[\w_.]+" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="propertyType.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
			<xsd:whiteSpace value="collapse" />
			<xsd:pattern value="[\w_]+" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="empty_trimmed_string.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="0" />
			<xsd:whiteSpace value="collapse" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="dataType.t">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="BOOLEAN" />
			<xsd:enumeration value="INTEGER" />
			<xsd:enumeration value="DOUBLE" />
			<xsd:enumeration value="STRING" />
			<xsd:enumeration value="ID" />
			<xsd:enumeration value="DATETIME" />
			<xsd:enumeration value="URI" />
			<xsd:enumeration value="HTML" />
			<xsd:enumeration value="OTHER" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="attributeBase.t">
		<xsd:attribute name="name" type="tns:propertyName.t" use="required" />
		<xsd:attribute name="dataType" type="tns:dataType.t" use="required" />
	</xsd:complexType>

	<xsd:complexType name="attributeDef.t">
		<xsd:complexContent>
			<xsd:extension base="tns:attributeBase.t">
				<xsd:attribute name="length" type="tns:positiveInt.t" use="optional" />
				<xsd:attribute name="repeating" type="xsd:boolean" use="optional" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="attribute.t">
		<xsd:complexContent>
			<xsd:extension base="tns:attributeBase.t">
				<xsd:sequence>
					<xsd:element name="value" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="typeDef.t">
		<xsd:sequence>
			<xsd:element name="name" type="tns:trimmed_string.t" minOccurs="1" maxOccurs="1" />
			<xsd:element name="superType" type="tns:trimmed_string.t" minOccurs="0" maxOccurs="1" />
			<xsd:element name="attributes" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="attribute" type="tns:attributeDef.t" minOccurs="0" maxOccurs="unbounded" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="types.t">
		<xsd:sequence>
			<xsd:element name="type" type="tns:typeDef.t" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="types" type="tns:types.t" />

	<xsd:complexType name="user.t">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1" />
			<xsd:element name="defaultFolder" type="xsd:string" minOccurs="1" maxOccurs="1" />
			<xsd:element name="description" type="xsd:string" minOccurs="1" maxOccurs="1" />
			<xsd:element name="email" type="xsd:string" minOccurs="1" maxOccurs="1" />
			<xsd:element name="loginName" type="xsd:string" minOccurs="1" maxOccurs="1" />
			<xsd:element name="loginDomain" type="xsd:string" minOccurs="1" maxOccurs="1" />
			<xsd:element name="osName" type="xsd:string" minOccurs="1" maxOccurs="1" />
			<xsd:element name="osDomain" type="xsd:string" minOccurs="1" maxOccurs="1" />
			<xsd:element name="defaultAcl" type="xsd:string" minOccurs="1" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="users.t">
		<xsd:sequence>
			<xsd:element name="user" type="tns:user.t" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="users" type="tns:users.t" />

	<xsd:complexType name="group.t">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1" />
			<xsd:element name="type" type="xsd:string" minOccurs="1" maxOccurs="1" />
			<xsd:element name="email" type="xsd:string" minOccurs="1" maxOccurs="1" />
			<xsd:element name="administrator" type="xsd:string" minOccurs="1" maxOccurs="1" />
			<xsd:element name="displayName" type="xsd:string" minOccurs="1" maxOccurs="1" />
			<xsd:element name="public" type="xsd:boolean" minOccurs="1" maxOccurs="1" />
			<xsd:element name="users" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="user" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="groups" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="group" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="groups.t">
		<xsd:sequence>
			<xsd:element name="group" type="tns:group.t" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="groups" type="tns:groups.t" />
</xsd:schema>

=== Armedia/Caliente/engine/impl/trunk/src/test/resources/sample-groups.xml
<?xml version="1.0" encoding="UTF-8"?>
<groups
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.armedia.com/ns/cmf/engines/xml/import"
	xsi:schemaLocation="http://www.armedia.com/ns/cmf/engines/xml/import import.xsd ">
	<group>
		<name>name</name>
		<type>type</type>
		<email>email</email>
		<administrator>administrator</administrator>
		<displayName>displayName</displayName>
		<users>
			<user>user</user>
		</users>
		<groups>
			<group>group</group>
		</groups>
	</group>
</groups>

=== Armedia/Caliente/engine/impl/trunk/src/test/resources/sample-users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.armedia.com/ns/cmf/engines/xml/import"
	xsi:schemaLocation="http://www.armedia.com/ns/cmf/engines/xml/import import.xsd ">
	<user>
		<name>name</name>
		<defaultFolder>defaultFolder</defaultFolder>
		<description>description</description>
		<email>email</email>
		<loginName>loginName</loginName>
		<loginDomain>loginDomain</loginDomain>
		<osName>osName</osName>
		<osDomain>osDomain</osDomain>
	</user>
</users>
