=== Armedia/Caliente/cli/dctm-datagen/src/main/resources/data-generator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd"
	targetNamespace="http://www.armedia.com/ns/caliente/tools/data-generator"
	xmlns:tns="http://www.armedia.com/ns/caliente/tools/data-generator" elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0">

	<xsd:simpleType name="trimmed_string.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
			<xsd:whiteSpace value="collapse" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="id_string.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
			<xsd:whiteSpace value="collapse" />
			<xsd:pattern value="[\w_]+"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="empty_trimmed_string.t">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="0" />
			<xsd:whiteSpace value="collapse" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="value.t">
		<xsd:simpleContent>
			<xsd:extension base="tns:trimmed_string.t"/>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="attribute.t">
		<xsd:sequence>
			<xsd:element name="value" type="tns:value.t" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="name" type="tns:trimmed_string.t" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="attributes.t">
		<xsd:sequence>
			<xsd:element name="attribute" type="tns:attribute.t" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="url_content.t">
		<xsd:simpleContent>
			<xsd:extension base="xsd:anyURI"/>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="generated_content.t">
		<xsd:sequence>
			<xsd:any minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="engine" type="tns:trimmed_string.t" use="optional"/>
	</xsd:complexType>

	<xsd:complexType name="page.t">
		<xsd:choice minOccurs="1" maxOccurs="1">
			<xsd:element name="url" type="tns:url_content.t"/>
			<xsd:element name="generated" type="tns:generated_content.t"/>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="content.t">
		<xsd:sequence>
			<xsd:element name="page" type="tns:page.t" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="rendition.t">
		<xsd:complexContent>
			<xsd:extension base="tns:content.t">
				<xsd:attribute name="id" type="tns:trimmed_string.t" use="required"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="fs_object.t">
		<xsd:sequence>
			<xsd:element name="attributes" type="tns:attributes.t" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
		<xsd:attribute name="type" type="tns:trimmed_string.t" use="optional"/>
		<xsd:attribute name="name" type="tns:trimmed_string.t" use="optional"/>
	</xsd:complexType>

	<xsd:complexType name="document.t">
		<xsd:complexContent>
			<xsd:extension base="tns:fs_object.t">
				<xsd:sequence>
					<xsd:element name="content" type="tns:content.t" minOccurs="0" maxOccurs="1" />
					<xsd:element name="rendition" type="tns:rendition.t" minOccurs="0" maxOccurs="unbounded" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="folder.t">
		<xsd:complexContent>
			<xsd:extension base="tns:fs_object.t">
				<xsd:sequence>
					<xsd:choice minOccurs="0" maxOccurs="unbounded">
						<xsd:element name="folder" type="tns:folder.t" minOccurs="0" maxOccurs="unbounded" />
						<xsd:element name="document" type="tns:document.t" minOccurs="0" maxOccurs="unbounded"/>
					</xsd:choice>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="generation_plan.t">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="folder" type="tns:folder.t" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="document" type="tns:document.t" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="generation-plan" type="tns:generation_plan.t"/>
</xsd:schema>

=== Armedia/Caliente/cli/datagen/src/test/resources/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<generation-plan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.armedia.com/ns/data-generator"
	xsi:schemaLocation="http://www.armedia.com/ns/data-generator platform:/resource/caliente-cli-datagen/src/main/resources/data-generator.xsd">
	<folder name="xxx" type="ff" />
	<document name="xxx" type="ddd">
		<attributes>
			<attribute name="ddd">
				<value>value</value>
			</attribute>
		</attributes>
		<content>
			<page>
				<url>http://tempuri.org</url>
			</page>
		</content>
		<rendition id="xxxx">
			<page>
				<url>http://tempuri.org</url>
			</page>
		</rendition>
	</document>
	<folder name="xxx" type="ff" />
	<folder name="xxx" type="ff" />
	<folder name="xxx" type="ff" />
	<document name="xxx" type="ddd">
		<attributes>
			<attribute name="ddd">
				<value>value</value>
			</attribute>
		</attributes>
		<content>
			<page>
				<url>http://tempuri.org</url>
			</page>
		</content>
		<rendition id="xxxx">
			<page>
				<url>http://tempuri.org</url>
			</page>
		</rendition>
	</document>
</generation-plan>
